//! Definitions from `<c3d/texenv.h>`.
//!
//! Most of these functions are `static inline` so they don't get generated by `bindgen`.
//! See <https://github.com/rust-lang/rust-bindgen/issues/1090>.

use core::ops::{BitOr, Shl};

use ctru_sys::{GPU_COMBINEFUNC, GPU_PREVIOUS, GPU_REPLACE, GPU_TEVSCALE_1, GPU_TEVSRC};
use libc::c_int;

use super::*;

// TODO: why are these two different macros in C?

/// Creates a texture combiner source parameter from three sources.
#[inline]
fn GPU_TEVSOURCES<T>(a: T, b: T, c: T) -> T
where
    T: BitOr<Output = T> + Shl<u8, Output = T>,
{
    a | b << 4 | c << 8
}

/// Creates a texture combiner operand parameter from three operands.
#[inline]
fn GPU_TEVOPERANDS<T>(a: T, b: T, c: T) -> T
where
    T: BitOr<Output = T> + Shl<u8, Output = T>,
{
    a | b << 4 | c << 8
}

#[inline]
pub unsafe fn C3D_TexEnvInit(env: *mut C3D_TexEnv) {
    (*env).srcRgb = GPU_TEVSOURCES(GPU_PREVIOUS, 0, 0) as u16;
    (*env).srcAlpha = (*env).srcRgb;
    (*env).__bindgen_anon_1.opAll = 0;
    (*env).funcRgb = GPU_REPLACE as u16;
    (*env).funcAlpha = (*env).funcRgb;
    (*env).color = 0xFFFFFFFF;
    (*env).scaleRgb = GPU_TEVSCALE_1 as u16;
    (*env).scaleAlpha = GPU_TEVSCALE_1 as u16;
}

#[inline]
pub unsafe fn C3D_TexEnvSrc(
    env: *mut C3D_TexEnv,
    mode: C3D_TexEnvMode,
    s1: GPU_TEVSRC,
    s2: GPU_TEVSRC, // default GPU_PRIMARY_COLOR
    s3: GPU_TEVSRC, // default GPU_PRIMARY_COLOR
) {
    let param = GPU_TEVSOURCES(s1, s2, s3);

    if mode & C3D_RGB != 0 {
        (*env).srcRgb = param as u16;
    }

    if mode & C3D_Alpha != 0 {
        (*env).srcAlpha = param as u16;
    }
}

// TODO: match API of texenv.h
#[inline]
pub unsafe fn C3D_TexEnvOp(
    env: *mut C3D_TexEnv,
    mode: C3D_TexEnvMode,
    o1: c_int,
    o2: c_int,
    o3: c_int,
) {
    let param = GPU_TEVOPERANDS(o1, o2, o3);

    if mode & C3D_RGB != 0 {
        // (*env).opRgb = param as u16;
        (*env)
            .__bindgen_anon_1
            .__bindgen_anon_1
            .set_opRgb(param as u32);
    }

    if mode & C3D_Alpha != 0 {
        (*env)
            .__bindgen_anon_1
            .__bindgen_anon_1
            .set_opAlpha(param as u32);
    }
}

#[inline]
pub unsafe fn C3D_TexEnvFunc(env: *mut C3D_TexEnv, mode: C3D_TexEnvMode, param: GPU_COMBINEFUNC) {
    if mode & C3D_RGB != 0 {
        (*env).funcRgb = param as u16;
    }

    if mode & C3D_Alpha != 0 {
        (*env).funcAlpha = param as u16;
    }
}
